### ISSUE TITLE
Add YAML support

### ISSUE THREAD

**Issue by UnnamedOrange** [puneetmatharu/cmake-format-lint-action#1]
It seems that cmake-format cannot deal with YAML file because of lack of the denpendency. The offcial website of cmake-format suggests:

```
pip install cmakelang[YAML]
```

But this action writes:

https://github.com/puneetmatharu/cmake-format-lint-action/blob/868082b20873d65687e64a4807ea342d1844c4c7/Dockerfile#L14

However, I'm not sure whether it's the hinge of the problem. Please investigate it. Thank you!

**Comment by puneetmatharu** [comment]
Patched. Thanks for pointing this out!
